import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { assemblePayload } from '../../src/website-audit/assemble.js';
import { getRecoMatrix } from '../../src/website-audit/agent.js';
import { ConstatsSchema, AuditPayloadSchema, type Constats } from '../../src/website-audit/types.js';

const here = dirname(fileURLToPath(import.meta.url));
const readJson = (name: string): unknown =>
  JSON.parse(readFileSync(join(here, 'fixtures', name), 'utf8'));

describe('assemblePayload (parity with assemble_reco.py)', () => {
  it('reproduces the Python assembler output byte for byte', () => {
    // payload-golden.json is generated by the ORIGINAL Python script:
    //   python3 .claude/skills/check-conformite-site-courtier/scripts/assemble_reco.py \
    //     fixtures/constats-fixture.json src/website-audit/data/recommandations.json \
    //     --out fixtures/payload-golden.json
    // Regenerate it whenever the fixture or the matrix changes.
    const constats = ConstatsSchema.parse(readJson('constats-fixture.json'));
    const golden = readJson('payload-golden.json');
    const payload = assemblePayload(constats, getRecoMatrix());
    expect(payload).toEqual(golden);
  });

  it('validates against the payload schema', () => {
    const constats = ConstatsSchema.parse(readJson('constats-fixture.json'));
    const payload = assemblePayload(constats, getRecoMatrix());
    expect(() => AuditPayloadSchema.parse(payload)).not.toThrow();
  });

  it('renders every matrix sub-section even when constats are empty', () => {
    const payload = assemblePayload({ constats: {} } as Constats, getRecoMatrix());
    expect(payload.findings).toHaveLength(23);
    expect(payload.findings.every((f) => f.level === 'a_verifier')).toBe(true);
    expect(payload.summary).toEqual({ critiques: 0, ameliorations: 0, conformes: 0, aVerifier: 23 });
  });

  it('rejects an invalid verdict like the Python script does', () => {
    const constats = {
      constats: { P07: { applicable: true, checks: [{ id: 'P07.1', verdict: 'nope' }] } },
    } as unknown as Constats;
    expect(() => assemblePayload(constats, getRecoMatrix())).toThrow(/Verdict invalide P07\/P07\.1/);
  });
});
